name: tox

on:
  push:
    branches:
      - "**"
  pull_request:
  schedule:
    - cron: 1 0 * * *  # Run daily at 0:01 UTC

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        envlist: [lint, packaging]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install tox
      - run: python -m tox -e ${{ matrix.envlist }}

  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
        molecule: [stable, devel]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Set tox envlist
        run: echo "envlist=py$(echo ${{ matrix.python }} | tr -d '.')-${{ matrix.molecule }}" >> $GITHUB_ENV
      - run: python -m pip install tox
      - run: python -m tox -e ${{ env.envlist }}
