name: tox

on:
  push:
    branches:
      - "**"
  pull_request:
  release:
    types:
      - published
  schedule:
    - cron: 1 0 * * *  # Run daily at 0:01 UTC

jobs:
  Base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        envlist: [lint, packaging]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: python -m pip install tox
      - run: python -m tox -e ${{ matrix.envlist }}

  Test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: [3.6, 3.7, 3.8, 3.9]
        molecule: [stable, devel]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Set tox envlist
        run: echo "envlist=py$(echo ${{ matrix.python }} | tr -d '.')-${{ matrix.molecule }}" >> $GITHUB_ENV
      - run: python -m pip install tox
      - run: PYTEST_REQPASS=3 python -m tox -e ${{ env.envlist }}

  Publish:
    needs: [Base, Test]
    runs-on: ubuntu-latest
    if: >-
      github.repository_owner == 'ansible-community' &&
      contains('push release', github.event_name) &&
      (
        startsWith(github.ref, 'refs/tags/') ||
        github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
      )
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - run: python -m pip install tox
      - name: Publish to test.pypi.org
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        run: python -m tox -e publish
        env:
          TWINE_PASSWORD: ${{ secrets.testpypi_password }}
          TWINE_REPOSITORY_URL: https://test.pypi.org/legacy/
      - name: Publish to pypi.org
        if: startsWith(github.ref, 'refs/tags/')
        run: python -m tox -e publish
        env:
          TWINE_PASSWORD: ${{ secrets.pypi_password }}
