name: tox

on:
  create:  # is used for publishing to TestPyPI
    tags:  # any tag regardless of its name, no branches
      - "**"
  push:  # only publishes pushes to the main branch to TestPyPI
    branches:  # any integration branch but not tag
      - "main"
  pull_request:
  release:
    types:
      - published  # It seems that you can publish directly without creating
  schedule:
    - cron: 1 0 * * *  # Run daily at 0:01 UTC

jobs:
  build:
    name: ${{ matrix.name }}
    # ubuntu-latest is current older and we need last podman toolkit.
    # https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: lint
            tox_env: lint
            python-version: 3.8
          - name: dockerfile
            tox_env: dockerfile
            python-version: 3.8
          - name: packaging
            tox_env: packaging
            python-version: 3.8
          # - tox_env: docs
          - name: py38
            tox_env: py38,py38-devel
            PREFIX: PYTEST_REQPASS=3
            python-version: 3.8
          - name: py39
            tox_env: py39,py39-devel
            PREFIX: PYTEST_REQPASS=3
            python-version: 3.9

    steps:
      - name: Check out src from Git
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # needed by setuptools-scm

      - name: Enable caching of ~/.cache/pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ matrix.name }}-${{ hashFiles('**/setup.cfg', 'tox.ini', '.github/workflows/tox.yml') }}

      - name: Enable caching of ~/.cache/pre-commit
        uses: actions/cache@v2
        with:
          path: ~/.cache/pre-commit
          key: ${{ matrix.name }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Enable caching for ansible tools
        uses: actions/cache@v2
        with:
          path: |
            ~/.ansible/collections
            ~/.ansible/galaxy_cache
            ~/.cache/ansible-compat
          key: ${{ hashFiles('requirements.yml') }}

      - name: Install system dependencies
        # community.docker requires docker>=5.0.0 but ubuntu has older
        run: |
          set -ex
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh
          sudo apt-get update
          docker --version
          docker info

      # Even our lint and other envs need access to tox
      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          docker version
          docker info
          python -m pip install -U "pip>=21.2.4" "tox>=3.24.2"

      - name: Run tox -e ${{ matrix.tox_env }}
        run: |
          echo "${{ matrix.PREFIX }} tox -e ${{ matrix.tox_env }}"
          ${{ matrix.PREFIX }} tox -e ${{ matrix.tox_env }}
